version: 2
jobs:
  build:
    working_directory: ~/boogie-solver
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test-unit
          command: npm run test:unit
      - run:
          name: compile
          command: npm run build:compile
      - store_artifacts:
          path: test-results/tap.xml
      - store_artifacts:
          path: ./coverage/lcov.info
          prefix: test-results
      - store_test_results:
          path: test-results/tap.xml
